command:
  - streamlit
  - run
  - app.py
env:
  - name: DATABRICKS_HOST
    value: "{{secrets/rh-demo/databricks-host}}"
  - name: SP_CLIENT_ID
    value: "{{secrets/rh-demo/sp-client-id}}"
  - name: SP_CLIENT_SECRET
    value: "{{secrets/rh-demo/sp-client-secret}}"