command:
  - streamlit
  - run
  - app.py
env:
  - name: DATABRICKS_HOST
    valueFrom: databricks-host
  - name: SP_CLIENT_ID
    valueFrom: sp-client-id
  - name: SP_CLIENT_SECRET
    valueFrom: sp-client-secret